
function findclick(id){
    let simple_list= {
        'ё': 'ё',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '0': '0',
        '-': '-',
        '=': '=',
        'Backspace': 'Backspace',
        'tab': 'Tab',
        'й': 'й',
        'ц': 'ц',
        'у': 'у',
        'к': 'к',
        'е': 'е',
        'н': 'н',
        'г': 'г',
        'ш': 'ш',
        'щ': 'щ',
        'з': 'з',
        'х': 'х',
        'ъ': 'ъ',
        '/': '/',
        'del': 'Del',
        'capslock': 'Capslock',
        'ф': 'ф',
        'ы': 'ы',
        'в': 'в',
        'а': 'а',
        'п': 'п',
        'р': 'р',
        'о': 'о',
        'л': 'л',
        'д': 'д',
        'ж': 'ж',
        'э': 'э',
        'enter': 'Enter',
        'lshift': 'left Shift',
        'rshift': 'right Shift',
        '/' : '/',
        'я': 'я',
        'ч': 'ч',
        'с': 'с',
        'м': 'м',
        'и': 'и',
        'т': 'т',
        'ь': 'ь',
        'б': 'б',
        'ю': 'ю',
        'up': 'up',
        'down': 'down',
        'left': 'left',
        'right': 'right',
        'lctrl': 'left ctrl',
        'rctrl': 'right ctrl',
        'lalt':'left alt',
        'ralt':'right alt',
        'win':'Win',
        'пробел':'Пробел'
    }
    console.log(simple_list[id])
}

